import type { Testimonial } from './types';

// ─── TESTIMONIALS ─────────────────────────────────────────────────────────────
export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Aarav Kapoor",
    avatar: "AK",
    rank: "AIR 247",
    exam: "JEE Advanced",
    year: "2024",
    text: "Dr. Sharma's Physics classes were a game changer. The way he explains electrostatics with real-world analogies made everything click. I went from 60% to 98% in Physics!",
    rating: 5,
    courseId: "course-jee-physics",
  },
  {
    id: "t2",
    name: "Sneha Patel",
    avatar: "SP",
    rank: "AIR 512",
    exam: "NEET",
    year: "2024",
    text: "Dr. Sunita's NEET Biology course is simply the best. Her NCERT annotation technique saved me weeks of revision time. Scored 350/360 in Biology!",
    rating: 5,
    courseId: "course-neet-biology",
  },
  {
    id: "t3",
    name: "Rohan Gupta",
    avatar: "RG",
    rank: "AIR 189",
    exam: "JEE Advanced",
    year: "2024",
    text: "Arjun sir's mathematics course transformed my approach. The speed-solving workshops are insane — I now solve integration problems in half the time.",
    rating: 5,
    courseId: "course-jee-maths",
  },
  {
    id: "t4",
    name: "Ananya Desai",
    avatar: "AD",
    rank: "AIR 334",
    exam: "JEE Main",
    year: "2025",
    text: "Priya ma'am makes Organic Chemistry feel like storytelling. Every reaction has a story and I never forget mechanisms anymore. 98/100 in Chemistry board!",
    rating: 5,
    courseId: "course-jee-chemistry",
  },
  {
    id: "t5",
    name: "Karan Singh",
    avatar: "KS",
    rank: "98.6 %ile",
    exam: "JEE Main",
    year: "2025",
    text: "Joined Illuster in Class 11 and never looked back. The structured approach, mock tests every week, and doubt sessions made all the difference.",
    rating: 5,
    courseId: "course-jee-physics",
  },
  {
    id: "t6",
    name: "Meera Joshi",
    avatar: "MJ",
    rank: "AIIMS Delhi",
    exam: "NEET",
    year: "2024",
    text: "The portal is so convenient — I could rewatch lectures when I was confused and download notes for offline study. Technology + great teaching = perfect combo.",
    rating: 5,
    courseId: "course-neet-biology",
  },
];
