import type { Course, Faculty, StudyMaterial } from './types';

export const courses: Course[] = [
  {
    id: "course-jee-physics",
    title: "JEE Physics Pro",
    subject: "Physics",
    targetClass: "Class 11 & 12",
    description:
      "Comprehensive JEE Physics covering Mechanics, Electrostatics, Optics, and Modern Physics with daily problem-solving sessions.",
    duration: "12 Months",
    schedule: "Mon / Wed / Fri — 6:00 PM to 8:00 PM",
    price: 24999,
    originalPrice: 34999,
    badge: "Best Seller",
    color: "#3B82F6",
    icon: "⚡",
    syllabus: [
      "Kinematics & Newton's Laws",
      "Work, Energy & Power",
      "Rotational Mechanics",
      "Gravitation & Fluid Mechanics",
      "Waves & Thermodynamics",
      "Electrostatics & Capacitance",
      "Current Electricity & Magnetism",
      "Electromagnetic Induction",
      "Optics — Ray & Wave",
      "Modern Physics & Nuclear",
    ],
    facultyId: "faculty-001",
    enrolledCount: 342,
    rating: 4.9,
    features: [
      "Live + Recorded Lectures",
      "Weekly Tests",
      "DPP (Daily Practice Problems)",
      "Doubt Sessions",
      "Study Materials",
    ],
  },
  {
    id: "course-jee-chemistry",
    title: "JEE Chemistry Master",
    subject: "Chemistry",
    targetClass: "Class 11 & 12",
    description:
      "Deep-dive into Physical, Organic, and Inorganic Chemistry with exam-focused shortcuts and reaction mechanisms.",
    duration: "12 Months",
    schedule: "Tue / Thu / Sat — 5:00 PM to 7:00 PM",
    price: 22999,
    originalPrice: 30999,
    badge: "Popular",
    color: "#10B981",
    icon: "🧪",
    syllabus: [
      "Mole Concept & Stoichiometry",
      "Atomic Structure & Bonding",
      "Thermodynamics & Equilibrium",
      "Electrochemistry & Kinetics",
      "Alkanes, Alkenes & Alkynes",
      "Aromatic Chemistry",
      "Biomolecules & Polymers",
      "s-Block & p-Block Elements",
      "d-Block & Coordination Chemistry",
      "Qualitative Analysis",
    ],
    facultyId: "faculty-002",
    enrolledCount: 289,
    rating: 4.8,
    features: [
      "Live + Recorded Lectures",
      "Formula Sheets",
      "Monthly Mock Tests",
      "Personal Mentoring",
      "PDF Notes",
    ],
  },
  {
    id: "course-jee-maths",
    title: "JEE Mathematics Elite",
    subject: "Mathematics",
    targetClass: "Class 11 & 12",
    description:
      "From Algebra to Calculus, this course builds razor-sharp problem-solving speed and accuracy for JEE Advanced.",
    duration: "12 Months",
    schedule: "Mon / Wed / Sat — 7:30 PM to 9:30 PM",
    price: 23999,
    originalPrice: 31999,
    color: "#8B5CF6",
    icon: "📐",
    syllabus: [
      "Sets, Relations & Functions",
      "Complex Numbers & Quadratics",
      "Permutations & Combinations",
      "Binomial Theorem & Sequences",
      "Trigonometry & Inverse Trig",
      "Coordinate Geometry",
      "3D Geometry & Vectors",
      "Limits, Continuity & Differentiability",
      "Applications of Derivatives",
      "Integration & Differential Equations",
    ],
    facultyId: "faculty-003",
    enrolledCount: 310,
    rating: 4.9,
    features: [
      "Live Classes",
      "Speed & Accuracy Drills",
      "Previous Year Papers",
      "Doubt Clearing Sessions",
      "Chapter-wise Tests",
    ],
  },
  {
    id: "course-neet-biology",
    title: "NEET Biology Intensive",
    subject: "Biology",
    targetClass: "Class 11 & 12",
    description:
      "Master Botany and Zoology with NCERT-based conceptual clarity and high-yield topic identification for NEET.",
    duration: "10 Months",
    schedule: "Tue / Thu / Sat — 4:00 PM to 6:00 PM",
    price: 19999,
    originalPrice: 27999,
    badge: "NEET Special",
    color: "#F59E0B",
    icon: "🌿",
    syllabus: [
      "Cell Biology & Biomolecules",
      "Plant Physiology",
      "Human Physiology Systems",
      "Reproduction & Genetics",
      "Evolution & Ecology",
      "Diversity in Living World",
      "Structural Organisation",
      "Biotechnology",
      "Biology in Human Welfare",
      "Ecology & Environment",
    ],
    facultyId: "faculty-004",
    enrolledCount: 256,
    rating: 4.7,
    features: [
      "Live + Recorded Lectures",
      "NCERT Mastery Notes",
      "NEET Mock Series",
      "Diagram Practice Sheets",
      "Weekly Revision",
    ],
  },
  {
    id: "course-class10-science",
    title: "Class 10 Science Booster",
    subject: "Science",
    targetClass: "Class 10",
    description:
      "Board-focused Science covering Physics, Chemistry, and Biology with exam strategies and full syllabus coverage.",
    duration: "8 Months",
    schedule: "Mon / Wed / Fri — 4:00 PM to 5:30 PM",
    price: 12999,
    originalPrice: 17999,
    badge: "Board Exam",
    color: "#EF4444",
    icon: "🔬",
    syllabus: [
      "Light & Human Eye",
      "Electricity & Magnetic Effects",
      "Chemical Reactions",
      "Acids, Bases & Salts",
      "Metals & Non-Metals",
      "Carbon Compounds",
      "Life Processes",
      "Control & Coordination",
      "Heredity & Evolution",
      "Ecosystems",
    ],
    facultyId: "faculty-001",
    enrolledCount: 198,
    rating: 4.8,
    features: [
      "Live Classes",
      "Board Paper Analysis",
      "Sample Paper Practice",
      "Chapter Summaries",
      "Parent Progress Reports",
    ],
  },
  {
    id: "course-foundation-8",
    title: "Foundation Course (Class 8)",
    subject: "Science & Maths",
    targetClass: "Class 8",
    description:
      "Early preparation course building a solid conceptual foundation in Science and Mathematics for future competitive exams.",
    duration: "6 Months",
    schedule: "Sat / Sun — 10:00 AM to 1:00 PM",
    price: 8999,
    originalPrice: 12999,
    color: "#06B6D4",
    icon: "🏗️",
    syllabus: [
      "Number Systems & Algebra",
      "Geometry & Mensuration",
      "Rational Numbers & Exponents",
      "Force & Pressure",
      "Chemical Reactions (Intro)",
      "Cell — Structure & Function",
      "Data Handling",
      "Playing with Numbers",
      "Light & Sound",
      "Conservation of Plants & Animals",
    ],
    facultyId: "faculty-003",
    enrolledCount: 145,
    rating: 4.6,
    features: [
      "Weekend Batches",
      "Olympiad Preparation",
      "Fun Learning Activities",
      "Concept Videos",
      "Monthly Assessments",
    ],
  },
];

// ─── FACULTY ──────────────────────────────────────────────────────────────────
export const faculty: Faculty[] = [
  {
    id: "faculty-001",
    name: "Dr. Rajesh Sharma",
    subject: "Physics",
    qualification: "Ph.D. Physics, IIT Delhi",
    experience: "14 Years",
    bio: "Former IIT professor with a passion for simplifying complex physics concepts. Dr. Sharma has guided 800+ students to IIT through his unique visualization approach.",
    avatar: "RS",
    achievements: [
      "100+ IIT Selections",
      "IIT Delhi Alumni",
      "Best Faculty Award 2023",
      "Author of 'Physics Demystified'",
    ],
    successRate: "94%",
    courseIds: ["course-jee-physics", "course-class10-science"],
  },
  {
    id: "faculty-002",
    name: "Ms. Priya Nair",
    subject: "Chemistry",
    qualification: "M.Sc. Chemistry, NIT Trichy",
    experience: "10 Years",
    bio: "Specialist in Organic Chemistry with an unmatched ability to make reaction mechanisms intuitive. Her students consistently score 95+ in Chemistry.",
    avatar: "PN",
    achievements: [
      "200+ NEET Selections",
      "NIT Gold Medalist",
      "JEE Chemistry Expert",
      "Rank 1 Producer 2022",
    ],
    successRate: "91%",
    courseIds: ["course-jee-chemistry"],
  },
  {
    id: "faculty-003",
    name: "Mr. Arjun Mehta",
    subject: "Mathematics",
    qualification: "B.Tech IIT Bombay, M.Tech NIT",
    experience: "12 Years",
    bio: "IIT Bombay alumnus with a knack for building mathematical intuition from the ground up. Known for his 'speed-solving' workshops that double student accuracy.",
    avatar: "AM",
    achievements: [
      "150+ IIT Selections",
      "IIT Bombay Rank 89",
      "Math Olympiad Coach",
      "Speed Maths Champion",
    ],
    successRate: "96%",
    courseIds: ["course-jee-maths", "course-foundation-8"],
  },
  {
    id: "faculty-004",
    name: "Dr. Sunita Rao",
    subject: "Biology",
    qualification: "MBBS + M.D., AIIMS Delhi",
    experience: "9 Years",
    bio: "AIIMS alumna who combines medical knowledge with pedagogy to make Biology concepts stick. Her NCERT-first approach has helped hundreds crack NEET with top scores.",
    avatar: "SR",
    achievements: [
      "300+ NEET Selections",
      "AIIMS Alumni",
      "NEET Biology Topper Coach",
      "Published Researcher",
    ],
    successRate: "89%",
    courseIds: ["course-neet-biology"],
  },
];

// ─── STUDY MATERIALS ─────────────────────────────────────────────────────────
export const studyMaterials: StudyMaterial[] = [
  // JEE Physics
  {
    id: "mat-001", courseId: "course-jee-physics", title: "Kinematics - Complete Notes", type: "pdf", size: "3.2 MB", chapter: "Chapter 1", uploadDate: "2024-06-01",
  },
  {
    id: "mat-002", courseId: "course-jee-physics", title: "Newton's Laws - Lecture 1", type: "video", duration: "1h 24m", chapter: "Chapter 2", uploadDate: "2024-06-03", watched: true,
  },
  {
    id: "mat-003", courseId: "course-jee-physics", title: "Newton's Laws - Lecture 2", type: "video", duration: "58m", chapter: "Chapter 2", uploadDate: "2024-06-05", watched: false,
  },
  {
    id: "mat-004", courseId: "course-jee-physics", title: "Chapter 1 & 2 Test", type: "test", chapter: "Chapter 1-2", uploadDate: "2024-06-10",
  },
  {
    id: "mat-005", courseId: "course-jee-physics", title: "Electrostatics Notes", type: "pdf", size: "4.1 MB", chapter: "Chapter 6", uploadDate: "2024-07-01",
  },
  // JEE Maths
  {
    id: "mat-006", courseId: "course-jee-maths", title: "Complex Numbers - Full Lecture", type: "video", duration: "2h 10m", chapter: "Chapter 2", uploadDate: "2024-06-02", watched: true,
  },
  {
    id: "mat-007", courseId: "course-jee-maths", title: "Quadratic Equations Notes", type: "pdf", size: "2.8 MB", chapter: "Chapter 2", uploadDate: "2024-06-04",
  },
  {
    id: "mat-008", courseId: "course-jee-maths", title: "Integration Master Sheet", type: "pdf", size: "5.5 MB", chapter: "Chapter 9", uploadDate: "2024-08-01",
  },
  {
    id: "mat-009", courseId: "course-jee-maths", title: "Mid-Term Mock Test", type: "test", chapter: "Ch 1-5", uploadDate: "2024-08-15",
  },
];
